apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: provisioner-eks
spec:
  disruption:
    consolidationPolicy: WhenEmpty #WhenUnderutilized
    consolidateAfter: 25s 
    expireAfter: 720h0m0s
  limits:
    cpu: 1k
    memory: 150Gi
  template:
    metadata:
      labels:
        intent: apps
    spec:
      nodeClassRef:
        name: provisioner-eks
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t2
        - t4g
        - r6g
        - r5
        - c6g
        - r6g
        - c5
        - c4
        - c5d
        - c5a
        - c5ad
        - c5n
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - small
        - medium
        - large
        - xlarge
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - ca-central-1a
        - ca-central-1b
        - ca-central-1d
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64