apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: provisioner-graviton
spec:
  disruption:
    consolidationPolicy: WhenEmpty #WhenUnderutilized
    consolidateAfter: 25s 
    expireAfter: 720h0m0s
  limits:
    cpu: 1k
    memory: 150Gi
  template:
    metadata:
      # annotations: # will be applied to all nodes
      #   karpenter.sh/do-not-disrupt: "true"
      labels:
        basic-node: graviton-pool #main-node
    spec:
      taints:
        - key:  graviton-pool #main-node
          effect: NoSchedule
      nodeClassRef:
        name: provisioner-graviton
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - is4gen
        - t4g
        - c6g
        - r6g
        - r7g
        - im4gn
        - c7g
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - medium
        - large
        - xlarge
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - ca-central-1a
        - ca-central-1b
        - ca-central-1d
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64